user nginx;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Logging settings
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Gzip Settings
    gzip on;

    server {
        # SSL configuration
        listen 443 ssl;
        listen [::]:443 ssl;

        # Substituted dynamically via envsubst from your .env
        server_name ${DOMAIN_NAME};

        # TLS certificates
        ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

        # Secure protocols requirements
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Root directory and index files
        root /var/www/html;
        index index.php index.html index.htm;

        # Docker's internal DNS server (Required for dynamic variable routing)
        resolver 127.0.0.11 valid=30s;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # Route PHP requests to the WordPress container dynamically
        location ~ \.php$ {
            try_files $uri =404;
            
            # $upstream_wordpress is ignored by envsubst and handled by Nginx at runtime.
            # ${WP_PORT} is replaced by envsubst during boot (9000).
            set $upstream_wordpress wordpress:${WP_PORT};
            
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass $upstream_wordpress;
            fastcgi_index index.php;
            
            # FastCGI parameters
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

		location /adminer/ {
			proxy_pass http://adminer:8080/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_redirect off;
		}

        location /static/ {
            set $upstream_static static:8081;
            proxy_pass http://$upstream_static/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

		location /portainer/ {
			proxy_pass http://portainer:9000/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_redirect off;
		}

        # Deny access to hidden files like .htaccess
        location ~ /\.ht {
            deny all;
        }
   }
}
