[ req ]
default_bits        = 2048
default_keyfile     = nginx-selfsigned.key
distinguished_name  = req_distinguished_name
prompt              = no
x509_extensions     = v3_ca

[ req_distinguished_name ]
C                   = FR
ST                  = IDF
L                   = Paris
O                   = 42
OU                  = Inception
CN                  = hermarti.42.fr

[ v3_ca ]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints       = critical, CA:true
keyUsage               = critical, digitalSignature, cRLSign, keyCertSign
