services:
  nginx:
    build: requirements/nginx
    image: nginx:inception
    container_name: nginx
    restart: on-failure
    ports:
        - "${WEB_PORT}:${WEB_PORT}"
    environment:
        - NGINX_HOST=${DOMAIN_NAME}
        - NGINX_PORT=${WEB_PORT}
    volumes:
        - ${VOLUME_WORDPRESS}:/var/www/html
    env_file:
        - .env
    networks:
        - inception_network

  mariadb:
    build: requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    restart: on-failure
    expose:
        - "${DB_PORT}"
    volumes:
        - ${VOLUME_MARIADB}:/var/lib/mysql
    env_file:
        - .env
    secrets:
        - db_name
        - db_user
        - db_password
        - db_root_password
    networks:
        - inception_network

  wordpress:
    build: requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    restart: on-failure
    expose:
        - "${WP_PORT}"
    volumes:
        - ${VOLUME_WORDPRESS}:/var/www/html
    depends_on:
        - mariadb
        - redis
    env_file:
        - .env
    secrets:
        - db_name
        - db_user
        - db_password
        - wp_admin_user
        - wp_admin_password
        - wp_user
        - wp_password
    networks:
        - inception_network

  redis:
    build: requirements/redis
    image: redis:inception
    container_name: redis
    restart: on-failure
    expose:
      - "${REDIS_PORT}"
    volumes:
      - ${VOLUME_REDIS}:/data
    env_file:
        - .env
    networks:
      - inception_network

  ftp:
    build: requirements/ftp
    image: ftp:inception
    container_name: ftp
    restart: on-failure
    ports:
      - "${FTP_PORT}:${FTP_PORT}"
      - "21000-21010:21000-21010"
    volumes:
      - ${VOLUME_WORDPRESS}:/var/www/html
    env_file:
      - .env
    secrets:
      - ftp_user
      - ftp_password
    networks:
      - inception_network

  adminer:
    build: requirements/adminer
    image: adminer:inception
    container_name: adminer
    restart: on-failure
    expose:
      - "${ADMINER_PORT}"
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception_network

  static:
    build: requirements/static
    image: static:inception
    container_name: static
    restart: on-failure
    expose:
      - "${STATIC_PORT}"
    env_file:
      - .env
    networks:
      - inception_network

  portainer:
    build: requirements/portainer
    image: portainer:inception
    container_name: portainer
    restart: on-failure
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_PORTAINER}:/data
    secrets:
      - portainer_password
      - portainer_user
    networks:
      - inception_network

secrets:
  db_name:
    file: ../secrets/db_name.txt
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user:
    file: ../secrets/wp_user.txt
  wp_password:
    file: ../secrets/wp_password.txt
  ftp_user:
    file: ../secrets/ftp_user.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
  portainer_user:
    file: ../secrets/portainer_user.txt
  portainer_password:
    file: ../secrets/portainer_password.txt

networks:
  inception_network:
    driver: bridge
